[http]
# Http Server Listen Address
# listen = "[::]:7777"
# Cross-Origin Resource Sharing (CORS)
# reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
# cors = false

[[ice_servers]]
urls = [
    "stun:stun.22333.fun",
    "stun:cn.22333.fun",
    "stun:stun.l.google.com:19302",
]

# [[ice_servers]]
# urls = [ "turn:turn.22333.fun", "turn:cn.22333.fun" ]
# username = "rust-server-for-multiplayer"
# credential = "rust-server-for-multiplayer"
# credential_type = "password"

# Headers["Authorization"] = "Bearer {token}"
# [auth]
# tokens = ["rust-server-for-multiplayer"]

# https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic
# Headers["Authorization"] = "Basic {Base64.encode({username}:{password})}"
# [[auth.accounts]]
# username = "rust-server-for-multiplayer"
# password = "rust-server-for-multiplayer"

[log]
# Env: `LOG_LEVEL`
# Default: info
# Values: off, error, warn, info, debug, trace
# level = "debug"
